---
 environment: <%= ENV.fetch('RACK_ENV', 'development') %>
 address: 0.0.0.0
 user: <%= `whoami` %>
 group: <%= `id -g -n` %>
 port: 3001
 pid: tmp/pids/thin.pid
 rackup: config.ru
 log: log/thin.log
 max_conns: 1024
 timeout: 30
 max_persistent_conns: 512
 daemonize: false
